hack4impact-calpoly/ecologistics-web-scraper

backend/api/urls.py
backend/api/views.py
backend/dj_api/settings.py
backend/dj_api/urls.py
backend/requirements.txt
frontend/package-lock.json
frontend/package.json
frontend/src/app/api/example/route.ts
frontend/src/app/example/page.tsx

feat: connect frontend to backend

---

frontend/src/styles/globals.css
frontend/tailwind.config.js

Closes #10 
Found primary/secondary/accent colors. Made a slight color change to the secondary, listed the original too in case. Read through ShadCn documentation to find out how to incorporate the colors. 
Modified global.css to add the color changes, tailwind.config.js remains unchanged for now. 
Tested changing the colors in global.css, right now changing the secondary color changes the navbar and footer bacgkround color, I set this to the seconday color i listed in the comment.

Feat: found colors and shadCn incoroporation

---

backend/api/app.py
backend/poetry.lock
backend/pyproject.toml

feat: init linter and formatter

---

README.md
backend/pyproject.toml

Closes #{n/a}
Added dev info to README

Modified README

---

.github/workflows/ci.yml
README.md

Closes #12 
Set up continuous integration through Github Actions.
ci.yml: Contains the continuous integration code
- Tested removing package.json file: ci failed as expected
- [] Code is neat, readable, and works

12 continuous integration

---

frontend/src/schemas/proposalSchema.ts

Created Proposal Schema
- created under src/schemas/proposalSchema
- verify formatting and content of the schema. 

commiting proposal schema

---

backend/api/app.py

Closes #23 
Chalice now grabs AWS credentials from the .env file
pip installed python dotenv
app.py: load the .env file to access/read the AWS credentials
ran: 
poetry run chalice deploy --> chalice local --> curl http://127.0.0.1:8000 (see screenshots)

23 set up aws chalice deployment

---

backend/makefile

Closes #18
Makefile for backend
Create a makefile that supports commands for poetry.

Makefile in backend

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/page.tsx
frontend/src/components/proposalTable.tsx
frontend/src/components/ui/table.tsx
frontend/src/lib/tableColumns.tsx

Closes #8 
Added a proposal table, along with pagination & sorting
components/proposalTable.tsx -> creates the proposal table, fetches data for it, and renders it. Currently have dummy data stored in this file. 
components/ui/table.tsx -> defines the table UI
lib/tableColumns.tsx -> defines the different columns for the table
- [X ] Code is neat, readable, and works
- [X ] Comments are appropriate
- [X ] The developer name is specified
- [X ] The summary is completed
- [X ] Assign reviewers

Proposal Table

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/navbar.tsx
frontend/src/styles/globals.css

Closes #27
Update navbar with bolded logo, logout using next auth signout, add welcome to the middle
* Unable to read vercel because of lack of access but i get ✔ No ESLint warnings or errors
why im not passing vercel

27 customize navbar

---

frontend/.husky/pre-commit

chore: fix pre-commit formatting hook

---

frontend/package-lock.json
frontend/src/Providers.tsx
frontend/src/app/(auth)/login/page.tsx
frontend/src/app/(auth)/signup/page.tsx
frontend/src/app/api/auth/[...nextauth]/options.ts
frontend/src/app/api/auth/[...nextauth]/route.ts
frontend/src/app/api/auth/route.ts
frontend/src/app/layout.tsx
frontend/src/app/page.tsx
frontend/src/components/navbar.tsx
frontend/src/middleware.ts

Closes #20 
Implemented NextAuth Login
Added [..nextauth].ts dynamic component
modified the signup function slightly in signup -> page.tsx
Added middleware.ts file to protect home route
Modified the navbar to implement a simple logout for testing
Tested signup -> login -> home route
Tested home route without being logged in
Tested logout

next auth signup

---

frontend/package-lock.json
frontend/src/app/(auth)/login/page.tsx
frontend/src/app/(auth)/signup/page.tsx

Closes #40 
Fix the styling of the signup and login buttons. Fixed the issue by changing the button variants to secondary instead of default, but there seems to be a problem rendering the primary color variable from the globals.css file. The primary color should be yellow/orange but renders as white or fails to render at all.
Changed the variant of the signup and login buttons to secondary instead of default.
Open the login and signup page and confirm the buttons render properly.

fix: fix signup and login button stylings

---

frontend/src/app/page.tsx
frontend/src/components/proposalTable.tsx

Closes #44
add simple title and description for what the table contains and where the data comes from.
Modified: proposalTable.tsx

Table description

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/(auth)/login/page.tsx
frontend/src/components/ui/alert.tsx

Closes #43 
Added functionality of non existing user and invalid credentials error messaging. 

43 add alert upon login with invalid credentials

---

backend/api/app.py
backend/api/routes/example.py
backend/api/routes/slo_county.py
backend/poetry.lock
backend/pyproject.toml

feat: setup beautiful soup

---

frontend/src/components/navbar.tsx

Closes #57 
Remove the home button from the navbar because the logo provides navigation back to homescreen
"src/components/navbar.tsx" removed text "Home" (which acted as a home button) from navbar
- [X ] Code is neat, readable, and works
- [X ] Comments are appropriate
- [X ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [X ] The developer name is specified
- [X ] The summary is completed
- [X ] Assign reviewers

refactor(navbar): removed the unneccesary home button from the navbar

---

backend/api/tests/example/test_example.py
backend/makefile

Closes #55 
Added sample unittest and configured makefile. 
Makefile, tests/example
Ran makefile command and observed unittest execution. 
- [ x] Code is neat, readable, and works
- [ x] Comments are appropriate
- [ x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ x] The developer name is specified
- [ x] The summary is completed
- [ x] Assign reviewers

feat: added unittest

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/proposalTable.tsx
frontend/src/components/ui/dialog.tsx
frontend/src/lib/tableColumns.tsx

Closes #49
Made rows have a dialog popup appear. 
Changed original request to instead of making the whole row clickable it instead is a more info button on each row. 
https://github.com/hack4impact-calpoly/ecologistics-web-scraper/assets/97003003/08576cce-c5ec-4f53-afbd-61ae7f84036e

49 make table rows clickable

---

frontend/src/app/(auth)/signup/page.tsx

Closes #54
Enforce the constraint that "Password must be at least 8 characters long and contain a number" with shadcn alert component. 
signup/page.tsx

commiting changes to enforce password constraints

---

backend/api/requirements.txt
backend/api/utils/slo_county/scrape_hearings.py

Closes #{48}
{make function that prints links after scraping from mentioned website}
{printed links because not sure how wanted to output and return links too}
{soooo i wasn't able to download the imports but it works in colab when i don't have trouble with downloading the imports. i updated the requirements file for the imports but i probably have to configure something on my end with vscode}
{<img width="748" alt="image" src="https://github.com/hack4impact-calpoly/ecologistics-web-scraper/assets/84148805/e52af192-3bb0-44ee-9ef2-74ef2d64497a">}

48 scraping

---

backend/api/routes/slo_county.py

Closes #65 
Created new endpoint at /slo_county/hearings in backend/api/routes/slo_county.
slo_county.py - endpoint added, commented out some code that could be used to store returned URLS in a mongo instance.
Tested endpoint using curl.

65-slo_county endpoint

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/proposalTable.tsx
frontend/src/components/ui/pagination.tsx

Closes #{71}
Add page pagination with row and page input
page pagination change to fit new standards
verify that page pagination works for multiple pages, first page, last page, page input, row input, page input doesn't go beyond what's available
for purposes of demonstrating page pagination, option to have only 1 row per page, delete

71 pagination

---

README.md
frontend/package-lock.json
frontend/package.json
frontend/src/app/page.tsx
frontend/src/components/scrapeButton.tsx
frontend/src/styles/globals.css

Closes #50 
Made the button become unclickable for 3 seconds upon being clicked. Replaced the text with an animated loading spinner for these 3 seconds, and then it goes back to normal. Just a note, the color of the loading spinner was meant to match the navbar color, but might be slightly off. 
Modified page.tsx to get rid of the existing button and abstract it out. 
Created a scrapeButton.tsx component to house the new button and hold the handleScrape async function
Nothing really to test, just make sure it works. Please also note, the className part of the spinner is marked as an error, but it doesn't actually cause an error. Not sure how to fix this, but the button works.

Completed loading spinner and button disabling

---

frontend/src/app/(auth)/signup/page.tsx

Closes #51 
Add email validation to the signup page
signup/page.tsx
1. Invalid email addresses throw an error message
2. Valid email addresses do not throw an error
3. If an invalid email address is entered, the error alert disappears when the user starts retyping the email address

feat: add email address validation to signup page

---

README.md

Closes #None
I made an error when adding my name to the readme, wanted to fix that with this PR
README
Nothing

read me structure fix

---

backend/api/routes/slo_county.py
frontend/src/components/scrapeButton.tsx

Closes #66 
Connected run webscraping button to the related backend route. 
**NOTE: For this issue, I enabled CORS for only the route to scrape hearings. There is a way to enable CORS globally for the API but I didn't look too far into it. 

connected button to backend route

---

frontend/src/app/about/page.tsx

Closes #59
Adding an about page + styling
added /app/about/page.tsx

feat about page commits

---

backend/api/utils/slo_county/scrape_sch.py

Closes #84 
Extract each project's SCH link and title on https://ceqanet.opr.ca.gov/Search?LeadAgency=San+Luis+Obispo+County&County=San+Luis+Obispo
Return data in a dictionary where key is project title and value is corresponding SCH link
Put webscraping function in scrape_sch.py 
Function returns correct data. However, error catching functionality wasn't tested as the current format of the page has no inconsistent/ missing data.

Scrape Title and SCH

---

frontend/src/app/(auth)/signup/page.tsx

Closes #79 
Updated sign up page to display correct error messages
(modified:   src/app/(auth)/signup/page.tsx)
- Ordering of error messages appearing 

feat: sign up page consist of necessary error messages

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/proposalTable.tsx

Closes #{83}
add search bar and selection for filter
{check filters}
{check filter, didn't filter dates because it wasn't working like everything else}

(feat): filter and select filter

---

backend/api/routes/slo_county.py

Closes #94 
Programmatically insert projects from scrape_hearings into test > projects collection on Mongodb
Created add_projects_to_mongo() in slo_county.py
Note: Function does **not** check if the document already exists in the database which can mean that duplicates will be added. One solution is to uncomment collection.drop() in the function but I wasn't sure if this was the best solution. Checking for existence would probably be more ideal, but I couldn't find an easy way to do this.

Add scraped projects to database

---

backend/api/chalicelib/utils/slo_county/scrape_hearings.py

Closes #98 
Only insert scraped hearings into test database hearings collection if it's not already there
/backend/api/chalicelib/utils/slo_county/scrape_hearings.py
Lines 57-64
When I call scrape_hearings(), the intended functionality occurs

Only Scrape unique hearings

---

frontend/src/components/proposalTable.tsx
frontend/src/lib/tableColumns.tsx

Closes #{110}
{Add filtering for other columns}
{
- Delete code that limited the filter options
- Make search bar display names with '_'
- switch name to title
}
{
-Tested filtering
}

extend package filtering

---

frontend/src/components/scrapeButton.tsx

Closes #121 
Added county and contact info to error message when websraper button fails.
src/components/scrapeButton.tsx
-> modified toast for error in handleScrape function
Tested by hitting endpoint without running the backend
- [x ] Code is neat, readable, and works
- [x ] Comments are appropriate
- [x ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x ] The developer name is specified
- [x ] The summary is completed
- [x ] Assign reviewers

Error messages and multiple counties

---

frontend/src/app/api/projects/route.ts

Closes #118 
Created POST method in api/projects/route.ts
Route updates review_status field in document based on county_file_number field.
Route does a basic check to make sure review status string is acceptable
Tested with curl

feat: add POST to api/projects/route.ts

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/proposalTable.tsx
frontend/src/components/ui/dropdown-menu.tsx
frontend/src/components/ui/popover.tsx
frontend/src/components/ui/separator.tsx
frontend/src/lib/tableColumns.tsx

Closes #{119}
{to add code for review}

119 populate more info modal for each project

---

frontend/src/components/scrapeButton.tsx
frontend/src/components/ui/toast.tsx

Closes #131
Added green toast for success on updating table when scrapeButton is pressed. 
scrapeButton.tsx
toast.tsx

Commiting Green Toast

---

backend/api/chalicelib/mongodb.py
backend/api/chalicelib/utils/clear_mongodb.py

Created a script that deletes content inside the database collections specified. 
clear_mondodb.py
mongodb.py

135 add a script to wipe database

---

backend/api/chalicelib/mongodb.py
backend/api/clear_mongodb.py

refactor backend

---

frontend/src/components/proposalTable.tsx

Closes #148 
Added spacing between the colored buttons for each status and centered the text. 
Additionally, made the buttons slightly longer so they didn't look scrunched.
PropsalTable.tsx was modified - changed the styling in each DropdownMenuItem component. 
The buttons look spaced and cleaner, test it looks as expected.

Changed Review status UI 

---

frontend/src/app/api/projects/route.ts
frontend/src/database/projectSchema.ts
frontend/src/lib/tableColumns.tsx

Updated the projects schema to match the field names used in the database.
Improved POST endpoint in projects/routes.ts
ensured that updating review status was reflected in the database

fix: updated project schema to match database. fix routes

---

frontend/src/app/api/projects/route.ts
frontend/src/components/proposalTable.tsx
frontend/src/components/ui/textarea.tsx
frontend/src/lib/tableColumns.tsx
package-lock.json

Closes #125 
Added additional notes textbox on frontend and created patch request function, connected the two to send to db
tableColumns.tsx
route.ts
textarea.tsx (new added)
tested that it hits endpoint, i guess check if it's acc in db?

125 additional notes
